###
 # THIS FILE IS AUTOMATICALLY GENERATED
 # Do not edit this file. It will be overwritten when the configure script is run.
###

######
# Build ID: 378eda8583286984
# Executable: ./bin/next_line_tlb
# Module Names: ('btbDbasic_btb', 'branchDbimodal', 'branchDgshare', 'branchDhashed_perceptron', 'branchDperceptron', 'prefetcherDip_stride', 'prefetcherDnext_line', 'prefetcherDnext_line_tlb', 'prefetcherDno', 'prefetcherDno_instr', 'prefetcherDspp_dev', 'prefetcherDva_ampm_lite', 'replacementDdrrip', 'replacementDlru', 'replacementDrandom', 'replacementDship', 'replacementDsrrip')
######

BIN_ROOT := bin
$(BIN_ROOT)/next_line_tlb: build_id := 378eda8583286984
nonbase_module_objs += $(filter-out $(base_module_objs),$(call get_module_list, btb/basic_btb \
  branch/bimodal branch/gshare branch/hashed_perceptron \
  branch/perceptron prefetcher/ip_stride prefetcher/next_line \
  prefetcher/next_line_tlb prefetcher/no prefetcher/no_instr \
  prefetcher/spp_dev prefetcher/va_ampm_lite replacement/drrip \
  replacement/lru replacement/random replacement/ship \
  replacement/srrip ))
executable_name += $(BIN_ROOT)/next_line_tlb
